# Generated by Django 6.0.6 on 2026-06-22 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('transfer', 'Transferencia Bancaria')], max_length=20, verbose_name='Método')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Referencia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('status', models.CharField(choices=[('approved', 'Aprobado'), ('pending', 'Pendiente'), ('rejected', 'Rechazado')], default='approved', max_length=20, verbose_name='Estado')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('payer_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del pagador')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del pagador')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='billing.invoice', verbose_name='Factura')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='billing.payment', verbose_name='Pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
